name = "Movie-related name sample"
description = "landing page description here"
keywords = "GIS, mapping, geo"
image = "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGd0bnptZnRycnp2OG14d3hxMTBvcGVuZ3JramNkbThqZm9sbmNxayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/VI2UC13hwWin1MIfmi/giphy.gif"
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
#gtag_id = "G-XLJ81DCZFV" (this is the google analytics tracking ID, current sample is the example from the original jake repo, not yours) 
base_url = "https://ymandal.github.io/"

[[sections]]
title = "Movies"
description = "Here are some of my movies I've seen"
direction = "column"
item_style = "outline"
[[sections.items]]
embed_url = "https://www.youtube.com/embed/x0gUY9ddjQY"
[[sections.items]]
title = "Nightcrawler"
description = "A mesmerizing thriller delving into the dark world of crime journalism"
url = "https://www.imdb.com/title/tt2872718/"
[[sections.items]]
title = "The Dark Knight"
description = "A trilogy piece of Batman's undertakings"
url = "https://www.imdb.com/title/tt0468569/"
[[sections.items]]
title = "Hot Fuzz"
description = "A comedy of unsuspecting coppers in a web of local secrets"
url = "https://www.imdb.com/title/tt0425112"


[[sections]]
title = "Links"
description = "Look for me on these websites"
direction = "row"
item_style = "filled"
icon_size = "30px"
[[sections.items]]
icon = "https://cdn.simpleicons.org/instagram/ffffff"
title = "Instagram"
url = "https://www.instagram.com/jakegyllenhaal"
[[sections.items]]
icon = "https://cdn.simpleicons.org/imdb/ffffff"
title = "IMDb"
url = "https://www.imdb.com/name/nm0350453/"
[[sections.items]]
icon = "https://cdn.simpleicons.org/wikipedia/ffffff"
title = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Jake_Gyllenhaal"
[[sections.items]]
title = "Rotten Tomatoes"
icon = "https://cdn.simpleicons.org/rottentomatoes/ffffff"
url = "https://www.rottentomatoes.com/celebrity/jake_gyllenhaal"
